#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

BACKEND_EXAMPLE="${PROJECT_ROOT}/backend/.env.example"
FRONTEND_EXAMPLE="${PROJECT_ROOT}/frontend/.env.example"
ROOT_ENV_EXAMPLE="${PROJECT_ROOT}/.env.example"

BACKEND_ENV="${PROJECT_ROOT}/backend/.env"
FRONTEND_ENV="${PROJECT_ROOT}/frontend/.env"
ROOT_ENV="${PROJECT_ROOT}/.env"

UNIT_SERVICE_PATH="/etc/systemd/system/hysteria-reload-on-config-change.service"
UNIT_PATH_PATH="/etc/systemd/system/hysteria-reload-on-config-change.path"

as_root() {
  if [[ "${EUID}" -eq 0 ]]; then
    "$@"
  else
    sudo "$@"
  fi
}

trim() {
  local value="$1"
  value="${value#"${value%%[![:space:]]*}"}"
  value="${value%"${value##*[![:space:]]}"}"
  printf "%s" "$value"
}

get_env_value() {
  local file_path="$1"
  local key="$2"
  if [[ ! -f "$file_path" ]]; then
    return 1
  fi
  local raw_line
  while IFS= read -r raw_line || [[ -n "$raw_line" ]]; do
    local line
    line="$(trim "$raw_line")"
    [[ -z "$line" || "$line" == \#* ]] && continue
    if [[ "$line" == "${key}="* ]]; then
      printf "%s" "${line#*=}"
      return 0
    fi
  done < "$file_path"
  return 1
}

collect_example_keys() {
  local example_file="$1"
  local -n out_keys="$2"
  out_keys=()
  while IFS= read -r line || [[ -n "$line" ]]; do
    line="$(trim "$line")"
    [[ -z "$line" || "$line" == \#* ]] && continue
    [[ "$line" != *=* ]] && continue
    out_keys+=("${line%%=*}")
  done < "$example_file"
}

prompt_yes_no() {
  local prompt_text="$1"
  local default_answer="${2:-y}"
  local suffix="[Y/n]"
  if [[ "$default_answer" == "n" ]]; then
    suffix="[y/N]"
  fi

  while true; do
    read -r -p "${prompt_text} ${suffix}: " answer
    answer="$(trim "$answer")"
    if [[ -z "$answer" ]]; then
      answer="$default_answer"
    fi
    case "${answer,,}" in
      y|yes) return 0 ;;
      n|no) return 1 ;;
      *) echo "Введите y или n." ;;
    esac
  done
}

configure_env_file() {
  local env_name="$1"
  local example_file="$2"
  local target_file="$3"

  if [[ ! -f "$example_file" ]]; then
    echo "Файл примера не найден: $example_file"
    exit 1
  fi

  if [[ -f "$target_file" ]]; then
    if ! prompt_yes_no "${env_name} уже существует. Перенастроить?" "y"; then
      echo "Пропущено: ${env_name}"
      return
    fi
  fi

  local example_keys=()
  collect_example_keys "$example_file" example_keys

  echo
  echo "=== Настройка ${env_name} ==="
  echo "Приоритет вопросов берется из порядка переменных в ${example_file##*/}"
  echo "Enter применяет значение из текущего ${env_name}, если есть; иначе из ${example_file##*/}"
  echo

  local tmp_file
  tmp_file="$(mktemp)"
  {
    echo "# Generated by deploy/setup.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
    echo
  } > "$tmp_file"

  local key default_value current_value user_value final_value
  for key in "${example_keys[@]}"; do
    current_value="$(get_env_value "$target_file" "$key" || true)"
    if [[ -n "$current_value" ]]; then
      default_value="$current_value"
    else
      default_value="$(get_env_value "$example_file" "$key" || true)"
    fi
    read -r -p "${key} (default: ${default_value}): " user_value
    if [[ -z "$user_value" ]]; then
      final_value="$default_value"
    else
      final_value="$user_value"
    fi
    printf "%s=%s\n" "$key" "$final_value" >> "$tmp_file"
  done

  command mv -f "$tmp_file" "$target_file"
  echo "Сохранено: ${target_file}"
  echo
}

setup_hysteria_reload_units() {
  local backend_hysteria_path
  backend_hysteria_path="$(get_env_value "$BACKEND_ENV" "HYSTERIA_CONFIG_PATH" || true)"
  [[ -z "$backend_hysteria_path" ]] && backend_hysteria_path="/etc/hysteria/config.yaml"

  local restart_cmd
  restart_cmd="$(get_env_value "$BACKEND_ENV" "HYSTERIA_RELOAD_COMMAND" || true)"
  if [[ -z "$restart_cmd" ]]; then
    restart_cmd="systemctl restart hysteria-server.service"
  fi

  echo
  echo "=== Настройка systemd для авто-перезапуска Hysteria ==="
  read -r -p "Путь до hysteria config (default: ${backend_hysteria_path}): " hysteria_path
  hysteria_path="${hysteria_path:-$backend_hysteria_path}"

  read -r -p "Команда перезапуска (default: ${restart_cmd}): " restart_command
  restart_command="${restart_command:-$restart_cmd}"

  local service_content path_content
  service_content="$(cat <<EOF
[Unit]
Description=Reload Hysteria when config changes

[Service]
Type=oneshot
ExecStart=/usr/bin/env bash -lc '${restart_command}'
EOF
)"

  path_content="$(cat <<EOF
[Unit]
Description=Watch ${hysteria_path} for changes

[Path]
PathChanged=${hysteria_path}
Unit=hysteria-reload-on-config-change.service

[Install]
WantedBy=multi-user.target
EOF
)"

  echo "$service_content" | as_root tee "$UNIT_SERVICE_PATH" > /dev/null
  echo "$path_content" | as_root tee "$UNIT_PATH_PATH" > /dev/null

  as_root systemctl daemon-reload
  as_root systemctl enable --now hysteria-reload-on-config-change.path

  echo "Службы обновлены и включены:"
  echo "  - $UNIT_SERVICE_PATH"
  echo "  - $UNIT_PATH_PATH"
}

main() {
  if [[ ! -f "${PROJECT_ROOT}/docker-compose.yml" ]]; then
    echo "Запускайте скрипт из репозитория vpn-auth."
    exit 1
  fi

  echo "=============================================="
  echo " VPN Auth VPS Setup (idempotent interactive) "
  echo "=============================================="
  echo

  echo "Шаг 1/4 (критично): корневой .env для docker-compose"
  configure_env_file ".env" "$ROOT_ENV_EXAMPLE" "$ROOT_ENV"

  echo "Шаг 2/4 (критично): backend/.env"
  configure_env_file "backend/.env" "$BACKEND_EXAMPLE" "$BACKEND_ENV"

  echo "Шаг 3/4 (менее критично): frontend/.env"
  configure_env_file "frontend/.env" "$FRONTEND_EXAMPLE" "$FRONTEND_ENV"

  echo "Шаг 4/4 (опционально): systemd watcher для Hysteria"
  if prompt_yes_no "Создать/обновить systemd path+service для авто-перезапуска Hysteria?" "n"; then
    setup_hysteria_reload_units
  else
    echo "Пропущено: настройка systemd watcher."
  fi

  echo
  echo "Готово."
  echo "Следующий шаг:"
  echo "  docker compose --env-file .env up -d --build --remove-orphans"
}

main "$@"
